<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/17 17:57:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/home/dave/jobeet/data/jobeet.db',
  'name' => 'doctrine',
)),);
