<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/18 07:54:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/home/dave/jobeet/data/jobeet_test.db',
  'name' => 'doctrine',
)),);
