# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings
prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
#ez az a rész ahova semmit sehogyan nem lehet beírni, különben kinyiffan a file
#kénytelen vagyok kihagyni a user autentikációt, egészen idáig tetszett a symfony
#megoldva, csak a netbeans rendetlenkedett
all:
  .actions:
    login_module:    sfGuardAuth
    login_action:    signin
  .settings:
     csrf_secret:            e8cd670b3b6cbb1b4b8b76c68e0c53dfc9bb72eb
     enabled_modules: [default, sfGuardAuth, sfGuardUser]
     escaping_strategy:      true
     escaping_method:        ESC_SPECIALCHARS
    
     use_database:           true
  