<?php

/**
 * JobeetCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetCategoryTable
     */
     public function doSelectForSlug($parameters)
        {
          return $this->findOneBySlugAndCulture($parameters['slug'], $parameters['sf_culture']);
        }

     public function findOneBySlugAndCulture($slug, $culture = 'en') //ez a fgv megkeresi az első kategóriát ami a culture-nek és a slugnak is megfelel 
        {
          $q = $this->createQuery('a')
            ->leftJoin('a.Translation t')
            ->andWhere('t.lang = ?', $culture)
            ->andWhere('t.slug = ?', $slug);
          return $q->fetchOne();
        }

     public function findOneBySlug($slug)
        {
          return $this->findOneBySlugAndCulture($slug, 'en');
        }
    
      
    public function getWithJobs() //kigyűjti kategóriánként az állásajánlatokat
    {
        $q = $this->createQuery('c')
          ->leftJoin('c.JobeetJobs j')
          ->where('j.expires_at > ?', date('Y-m-d H:i:s', time()));
        
        $q->andWhere('j.is_activated = ?', 1);

        return $q->execute();
    }
    
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetCategory');
    }
}